### ISSUE TITLE
Incorrect order of TLS1.3 ciphers

### ISSUE THREAD

**Issue by vitalygashkov** [Ossianaa/node-libcurl#15]
I came across a bug where the list of TLS ciphers for version 1.3 always comes in the same order. Moreover, this problem is present on macOS, but everything is correct on Windows.

For example, I am sending such `ja3`: 771,**4865-4866-4867**-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,65037-17513-65281-18-11-0-45-16-23-5-35-51-27-10-43-13,25497-29-23-24,0.

ja3 response (from https://tls.peet.ws/api/tls) comes like this: 771,**4867-4865-4866**-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,65037-17513-65281-18-11-0-45-16-23-5-35-51-27-10-43-13,25497-29-23-24,0.

As you can see, the first three TLS 1.3 ciphers did not return in the order in which I sent them when calling `fetch`.

**Comment by Ossianaa** [comment]
Fixed in v1.4.7, major patches have been uploaded to the [patches](https://github.com/Ossianaa/node-libcurl/tree/master/patches) directory.

**Comment by vitalygashkov** [comment]
> Fixed in v1.4.7, major patches have been uploaded to the [patches](https://github.com/Ossianaa/node-libcurl/tree/master/patches) directory.

Thanks. With your built addon everything works fine. 
But if I compile the Node.js addon myself, I get an error: `[1]    80384 segmentation fault`.

Maybe there are some differences in the `libcurl.a` files etc between the ones the addon published on npm was built with?
For reference, I'm using macOS on ARM (M1 Max).

**Comment by Ossianaa** [comment]
> > Fixed in v1.4.7, major patches have been uploaded to the [patches](https://github.com/Ossianaa/node-libcurl/tree/master/patches) directory.
> 
> Thanks. With your built addon everything works fine. But if I compile the Node.js addon myself, I get an error: `[1] 80384 segmentation fault`.
> 
> Maybe there are some differences in the `libcurl.a` files etc between the ones the addon published on npm was built with? For reference, I'm using macOS on ARM (M1 Max).

I used docker image [mcandre/snek](https://github.com/mcandre/snek) tag `x86_64-apple-darwin` `arm64-apple-darwin` to build the library for macOS. Since compilation is susceptible to environment variables and compilation options, I may upload the docker image for compilation in the future.

**Comment by vitalygashkov** [comment]
> I may upload the docker image for compilation in the future.

Yes, it would be nice for me to be able to build a correct .node addon myself. At the moment there seems to be some issues with the build process.

**Comment by vitalygashkov** [comment]
> major patches have been uploaded to the [patches](https://github.com/Ossianaa/node-libcurl/tree/master/patches) directory

I'm having trouble applying the patches :(
Could you please share the full sources of a project where I can build a modified `curl`?

**Comment by Ossianaa** [comment]
> > major patches have been uploaded to the [patches](https://github.com/Ossianaa/node-libcurl/tree/master/patches) directory
> 
> I'm having trouble applying the patches :( Could you please share the full sources of a project where I can build a modified `curl`?

some `Dockerfile` are pushed in [patches](https://github.com/Ossianaa/node-libcurl/tree/master/patches) directory.

**Comment by vitalygashkov** [comment]
> some `Dockerfile` are pushed in [patches](https://github.com/Ossianaa/node-libcurl/tree/master/patches) directory.

Thank you very much :)
