### ISSUE TITLE
Support Linux ARM64

### ISSUE THREAD

**Issue by TylorS** [Ossianaa/node-libcurl#19]
Hey there 👋 

First off, thank you for this wonderful library. It's been very helpful to me so far 😄 

I was wondering if it'd be possible to add support to Linux ARM64? This is the target I currently have in production, but it currently fails at `postinstall.js`

<img width="890" alt="Screenshot 2024-08-27 at 10 43 58 AM" src="https://github.com/user-attachments/assets/64ae2347-eaf1-4cfc-aa21-688ce9799700">

With a little bit of direction, I'm sure I'd be able to contribute this addition if it would be accepted.

**Comment by Ossianaa** [comment]
work in `v1.5.4`

**Comment by TylorS** [comment]
Thank you very much @Ossianaa ! I'll definitely give it a test and let you know if I run into anything else

**Comment by TylorS** [comment]
Hey @Ossianaa sorry for the long delay, been heads down building a new company 😄 

I can report that I still had some issues with segmentation faults on 1.5.4, but with 1.5.5 I'm not seeing any issues whatsoever! Thank you so much 🙏

**Comment by Ossianaa** [comment]
> Hey @Ossianaa sorry for the long delay, been heads down building a new company 😄
> 
> I can report that I still had some issues with segmentation faults on 1.5.4, but with 1.5.5+ I'm not seeing any issues whatsoever! Thank you so much 🙏

Thank you for your feedback. :)
