### ISSUE TITLE
okhttp4 android10 impersonate

### ISSUE THREAD

**Issue by mehmetuken** [Ossianaa/node-libcurl#20]
Hello, how can I use something like this in the example? And I didn't see an option for Akamai.

https://github.com/lexiforest/curl_cffi/blob/38a91f2e7b23d9c9bda1d8085b7e41e33767c768/examples/impersonate.py#L8

**Comment by Ossianaa** [comment]
work in `v1.5.5`

**Comment by mehmetuken** [comment]
Thanks a lot.
