### ISSUE TITLE
how to randomize ciphers?

### ISSUE THREAD

**Issue by j9a12c20k** [Ossianaa/node-libcurl#6]
Hello,

I love this library however, it seems it does not randomize tls extension order is there a way to do this? 

Thanks

**Comment by Ossianaa** [comment]
Are you trying to emulate the latest Chrome Tls extension?  If so, I will support this feature in the future :)

**Comment by j9a12c20k** [comment]
That is correct! Also thanks :)

**Comment by Ossianaa** [comment]
it's work in npm v1.1.0-alpha-4 now.
