### ISSUE TITLE
fetch模式下res['headers'].get('content-type')报错

### ISSUE THREAD

**Issue by tmxd09887** [Ossianaa/node-libcurl#9]
res.headers 返回[AsyncFunction: headers]
res['headers'].get('content-type')却报错了
res.headers.get is not a function

之前这么写是没问题的，最近突然报错了，请问是怎么回事

**Comment by Ossianaa** [comment]
请提供完整的调用代码和使用的版本号

**Comment by tmxd09887** [comment]
版本@ossiana/node-libcurl@1.1.3-alpha-5

代码
var res = await fetch(request_url,{
    httpVersion:1.1,
    headers:headers,
    method:"HEAD",
})

console.log(res['headers'].get('content-type'))

**Comment by Ossianaa** [comment]
使用前 先读.d.st文件 或者读源代码

https://github.com/Ossianaa/node-libcurl/blob/master/src/fetch.ts#L28
获取fetch后Response的方法都是异步方法

https://github.com/Ossianaa/node-libcurl/blob/master/src/libcurl.ts#L12
httpVersion的选择只有 0和1


```js
var res = await fetch(request_url,{
httpVersion:1,
headers:headers,
method:"HEAD",
});
console.log(await res.headers);//获取所有协议头
```

fetch的response.headers返回的是字符串 还不支持取指定协议头

**Comment by Ossianaa** [comment]
> 使用前 先读.d.st文件 或者读源代码
> 
> https://github.com/Ossianaa/node-libcurl/blob/master/src/fetch.ts#L28 获取fetch后Response的方法都是异步方法
> 
> https://github.com/Ossianaa/node-libcurl/blob/master/src/libcurl.ts#L12 httpVersion的选择只有 0和1
> 
> ```js
> var res = await fetch(request_url,{
> httpVersion:1,
> headers:headers,
> method:"HEAD",
> });
> console.log(await res.headers);//获取所有协议头
> ```
> 
> fetch的response.headers返回的是字符串 还不支持取指定协议头

推荐使用requests 它的功能更加齐全一点
